FROM node:lts-alpine

# Set the working directory
WORKdir /app

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set the command to run the app
CMD [ "npm", "run", "start" ]

